repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: [--config, pyproject.toml, --fix]
        exclude: ^huggingface/
      - id: ruff-format
        args: [--config, pyproject.toml]
        exclude: ^huggingface/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(modelgenerator/(huggingface_models|prot_inv_fold|rna_inv_fold|rna_ss|structure_tokenizer)|huggingface/)
      - id: end-of-file-fixer
        exclude: ^(modelgenerator/(huggingface_models|prot_inv_fold|rna_inv_fold|rna_ss|structure_tokenizer)|huggingface/)
      - id: check-yaml
        exclude: ^(modelgenerator/(huggingface_models|prot_inv_fold|rna_inv_fold|rna_ss|structure_tokenizer)|huggingface/)
      - id: debug-statements
        exclude: ^(modelgenerator/(huggingface_models|prot_inv_fold|rna_inv_fold|rna_ss|structure_tokenizer)|huggingface/)
      - id: check-added-large-files
        exclude: ^(modelgenerator/(huggingface_models|prot_inv_fold|rna_inv_fold|rna_ss|structure_tokenizer)|huggingface/)
